src/Entity/Pizza.php
<?php

namespace App\Entity;

use App\Repository\PizzaRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PizzaRepository::class)]
class Pizza
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 60)]
    private $name;

    #[ORM\ManyToOne(targetEntity: Size::class, inversedBy: 'pizza')]
    #[ORM\JoinColumn(nullable: false)]
    private $size;

    #[ORM\ManyToOne(targetEntity: Base::class, inversedBy: 'pizza')]
    #[ORM\JoinColumn(nullable: false)]
    private $base;

    #[ORM\ManyToMany(targetEntity: Topping::class, mappedBy: 'pizza', cascade: ['persist'], fetch: 'LAZY')]
    private $toppings;

    public function __construct()
    {
        $this->toppings = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getSize(): ?Size
    {
        return $this->size;
    }

    public function setSize(?Size $size): self
    {
        $this->size = $size;

        return $this;
    }

    public function getBase(): ?Base
    {
        return $this->base;
    }

    public function setBase(?Base $base): self
    {
        $this->base = $base;

        return $this;
    }

    /**
     * @return Collection<int, Topping>
     */
    public function getToppings(): Collection
    {
        return $this->toppings;
    }

    public function addTopping(Topping $topping): self
    {
        if (!$this->toppings->contains($topping)) {
            $this->toppings[] = $topping;
            $topping->addPizza($this);
        }

        return $this;
    }

    public function removeTopping(Topping $topping): self
    {
        if ($this->toppings->removeElement($topping)) {
            $topping->removePizza($this);
        }

        return $this;
    }

    public function getPrice()
    {
        $total = 0;

        foreach ($this->getToppings() as $topping){
            $total += $topping->getPrice();
        }
        return $total;
    }
}

src/Form/PizzaType.php
<?php

namespace App\Form;

use App\Entity\Base;
use App\Entity\Pizza;
use App\Entity\Size;
use App\Form\DataTransformer\ToppingDataTransformer;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;

use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;


class PizzaType extends AbstractType
{

private  ToppingDataTransformer $toppingDataTransformer;

    /**
     * @param ToppingDataTransformer $toppingDataTransformer
     */
    public function __construct(ToppingDataTransformer $toppingDataTransformer)
    {
        $this->toppingDataTransformer = $toppingDataTransformer;
    }


    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name')
           ->add('base',EntityType::class,[
               'class'=>Base::class,
               'choice_label'=>'name',
               'label'=>'Base',
           ])
            ->add('size', EntityType::class,[
                'class'=>Size::class,
                'choice_label'=>'size',
                'label'=>'Size',
            ])
            ->add('toppings',CollectionType::class,[
                'entry_type'=>PizzaToppingType::class,
                'allow_delete'=>true,
                'allow_add'=>true,
                'by_reference' => false,
                'label'=> false
            ]);

        $builder->get('toppings')->addModelTransformer($this->toppingDataTransformer);


//
//        ->add('toppings', CollectionType::class,[
//
//            'entry_type'=>PizzaToppingType::class,
//            'prototype'=>true,
//            'allow_add'=>true,
//            'allow_delete'=>true,
//            'label'=>false




    }


    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Pizza::class,


        ]);
    }
}

src/Controller/PizzaController.php
<?php

namespace App\Controller;

use App\Entity\Factory\OrderFactory;
use App\Entity\Order;
use App\Entity\OrderItem;
use App\Entity\Pizza;
use App\Form\AddToCartType;
use App\Form\CustomPizzaType;
use App\Form\PizzaType;
use App\Repository\OrderRepository;
use App\Repository\PizzaRepository;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/pizza')]
class PizzaController extends AbstractController
{
    #[Route('/', name: 'app_pizza_list')]
    public function list(PizzaRepository $pizzaRepository): Response
    {
        return $this->render('pizza/index.html.twig', [
            'pizzas' => $pizzaRepository->findAll(),
        ]);
    }



    #[Route('/{id<\d+>}', name: 'app_pizza_details', methods: ['GET'])]
    public function show(Request $request, Pizza $pizza): Response
        {
            $form  = $this->createForm(AddToCartType::class);
            $form->handleRequest($request);


            if ($form->isSubmitted() && $form->isValid()) {

                return $this->redirectToRoute('admin_pizza_list', [], Response::HTTP_SEE_OTHER);
            }


            return $this->render('/pizza/details.html.twig', [
                'pizza' => $pizza,
                'form'=>$form->createView()
            ]);
        }

    #[Route('/add/{id}', name: 'app_pizza_add', methods: ['GET'])]
    public function addOrderItem(Request $request,
                             Pizza $pizza,
                             UserRepository $userRepository,
    OrderRepository $orderRepository){
        // Rajouter un item a une commande de l'utilisateur de l'utilisateur

        $user = $userRepository->find($this->getUser());
        $orderFactory = new OrderFactory();
        $item = $orderFactory->createItem($pizza);
        //Chercher si il y'a déja une commande en cart pour ce user
        //Si oui, ajouter cet item dans cette commande, sinon en crée une nouvelle
        $test = $orderRepository->findOneBy(
            ['user'=>$this->getUser(),
                'status'=>Order::STATUS_CART
                ]
        );
       dump($test);

       if($test){

           $order = $test;
           $order->addItem($item);
           $orderRepository->add($order);
       }else{
           $order = $orderFactory->create();
           $order->setUser($user);
           $order->addItem($item);

       }


        $orderRepository->add($order);


        return $this->redirectToRoute('app_pizza_list'
        );

    }

    #[Route('/checkout', name: 'app_pizza_checkout', methods: ['GET'])]
    public function checkOut(Request $request,
                             Pizza $pizza,
                             UserRepository $userRepository,
                             OrderRepository $orderRepository){
        // Rajouter un item a une commande de l'utilisateur de l'utilisateur

        return $this->renderForm('home/index.html.twig'
        );

    }
    #[Route('/custom/new', name: 'app_pizza_custom', methods: ['GET','POST'])]
    public function customPizza(Request $request
                                ){

        $pizza = new Pizza();
        $form = $this->createForm(PizzaType::class, $pizza);
        $orderFactory = new OrderFactory();
        $test = $orderFactory->createitem($pizza);
        dump($test);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {


            return $this->redirectToRoute('app_pizza_list', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('/pizza/_form.html.twig', [
            'pizza' => $pizza,
            'form' => $form->createView(),
        ]);

    }

}

templates/pizza/_form.html.twig
{% block body %}
    <div class="col-md-8">


        {{ form_start(form) }}
        {{ form_row(form.name) }}
        {{ form_row(form.base) }}
        {{ form_row(form.size) }}



        <div>
            <h3>Toppings List</h3>
            <div class="d-flex justify-content-end">
                <button type="button" id="btnAddItem" class="btn btn-primary">
                    Ajouter un élément
                </button>
            </div>
            {{ form_row(form.toppings) }}
        </div>




        <button class="btn">{{ button_label|default('Save') }}</button>

        {{ form_end(form) }}
    </div>

    {{ encore_entry_script_tags('pizza.form') }}
{% endblock %}

templates/pizza/details.html.twig
{% extends 'base.html.twig' %}

{% block title %}Pizza{% endblock %}

{% block body %}
<div class="col-md-8">
<h1> {{ pizza.name }}</h1>
    <h1> {{ pizza.price }}</h1>
    {{ form_start(form,{'attr':{'class':'mt-4 p-4 bg-light'}} ) }}
  <div class="form-group">
{{ form_label(form.quantity) }}
      {{ form_widget(form.quantity,
          { 'attr':{
              'class':'form-control' ~ (form.quantity.vars.valid ?'':'is-invalid')
          }
          }
      ) }}
      <div class="invalid-feedback">
          {{ form_errors(form.quantity) }}
      </div>

      {{ form_widget(form.add) }}
      {{ form_end(form) }}
  </div>



    <a href="{{ path('app_pizza_list') }}">back to list</a>

    </div>
{% endblock %}

templates/pizza/index.html.twig
{% extends 'base.html.twig' %}

{% block title %} Pizza index{% endblock %}

{% block body %}
    <h1>Pizza index</h1>

    <table class="table">
        <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Ingrédients</th>
            <th>Price</th>
            <th>actions</th>
        </tr>
        </thead>
        <tbody>
        {% for pizza in pizzas %}
            <tr>
                <td>{{ pizza.id }}</td>
                <td>{{ pizza.name }}</td>
                <td>
                    {% for toppings in pizza.toppings %}
                        {{ toppings.name }},
                    {% endfor %}
                </td>
                <td>
                    {{ pizza.price }}
                </td>
                <td>
                    <a href="{{ path('app_pizza_details', {'id': pizza.id}) }}">Détails</a>
                    <a href="{{ path('app_pizza_add', {'id': pizza.id}) }}">Ajouter au pannier</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('admin_pizza_new') }}">Create new</a>
{% endblock %}

templates/pizza/new-custom.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Pizza{% endblock %}

{% block body %}
    <h1>Create new Pizza</h1>

    {{ include('pizza/_form.html.twig') }}

    <a href="{{ path('app_pizza_list') }}">back to list</a>
{% endblock %}

templates/pizza/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Pizza{% endblock %}

{% block body %}
    <h1>Create new Pizza</h1>

    {{ include('pizza/_form.html.twig') }}

    <a href="{{ path('app_pizza_index') }}">back to list</a>
{% endblock %}

templates/pizza/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Pizza{% endblock %}

{% block body %}
    <h1>Pizza</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ pizza.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ pizza.name }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_pizza_index') }}">back to list</a>

    <a href="{{ path('app_pizza_edit', {'id': pizza.id}) }}">edit</a>

    {{ include('pizza/_delete_form.html.twig') }}
{% endblock %}